DATA:
    ROOT: '/data/kinetics-dataset/k400'
    TRAIN_FILE: '/data/kinetics-dataset/csvs/k110/train.csv'
    VAL_FILE: '/data/kinetics-dataset/csvs/k110/test.csv'
    DATASET: kinetics110
    NUM_FRAMES: 32
    NUM_CLASSES: 110
    LABEL_LIST: 'labels/kinetics_110_labels.csv'
MODEL:
    ARCH: ViT-B/16
TRAIN:
    BATCH_SIZE: 4 # BS 512 = batchsize * numgpu * accumsteps
    ACCUMULATION_STEPS: 8
    LR: 8.0e-06
